apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx # Select pods with the label "app: nginx"
  ports:
  - protocol: TCP
    port: 80 # Port exposed by the service
    targetPort: 80 # Port to forward traffic to in the pods
  type: LoadBalancer